### ISSUE TITLE
V5 candidate updates

### ISSUE THREAD

**Issue by VJalili** [Genometric/GeUtilities#63]
- [x] Implement concrete and generic `IInterval` interface. [#67]
- [x] Rename from `IntervalParsers` to `Parsers\Interval`. [#68]
- [x] Define a boolean property (`ValidatePValue`) in BED parser which if set, the parser should validate p-values. A p-value must always fall in [0,1] range. Hence if either for p-value conversion format or an invalid input, the p-value of a parsed peak does not fall in this range, then the parser should either drop or keep the peak  based on the `ValidatePValue` property.  [#69]
- [x] Default models (e.g., ChIPSeqPeak) should implement `GetHashCode` function, and their hash key should be auto-generated/assigned. [#65]
- [x] All default types _must_ be immutable, and auto-generate hash code. Because these types can be used as dictionary keys with their hash key being their ID, and if the hash key is mutable, or not set (as it can happen now, because it is a user-set property), or not unique, it can cause issues in the dictionaries.  [#65]
- [x] Fix namespace naming issue in unit tests; [#68]
- [x] Refactor VCF parser; [#70]
- [x] Refactor RefSeq parser; [#70]
- [x] Refactor parsers to adhere with Pascal naming convention; [#70]
- [x] Override `Equals` for all the Default types; [#71]
- [x] Implement the `CompareTo` function of the `Interval` class; [#71]
- [x] The `CompareTo` functions of all the Default types can leverage the `CompareTo` function of the `Interval` class for base properties comparison. [#71]
